development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: ithaka_development
  pool:     5
  username: postgres
  password: 
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: ithaka_test
  pool:     5
  username: postgres
  password: 
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: ithaka_production
  pool:     5
  username: postgres
  password: 
  template: template0
