development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: votation_development
  pool:     5
  username: postgres
  password: 
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: votation_test
  pool:     5
  username: postgres
  password: 
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: votation_production
  pool:     5
  username: postgres
  password: 
  template: template0
